name: Upload to S3
on:
    workflow_dispatch:
    # push:
    #   branches:
    #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://nginx-evergreen-bucket --delete
